version: 2
jobs:
  build:
    working_directory: ~/cljsjs
    docker:
      - image: cljsjs/build-image:0.0.3
    steps:
      - checkout
      # No easy way to create checksum for cljsjs
      - restore_cache:
          key: cljsjs-v2
      - run: ./setup_gpg.sh
      - run: ./circle.sh
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: cljsjs-v2
    environment:
      BOOT_JVM_OPTIONS: "-Xms512m -Xmx1024m"
      NPM_CONFIG_LOGLEVEL: warn
